<p class="question">如何才能建立一座新的村庄？</p>
<p class="answer">
建立一座新的村庄，3个拓荒者和足够的文明点数是必要的，然后您就可以在地图上一个空白的方块上建村了。拓荒者无需研究即可训练，您只要把皇宫提升到10级、15级或20级，或者把行宫提升到10级或20级，都可以直接训练出拓荒者。修建皇宫，您需要先把中心大楼升到5级并且修建了大使馆，而修建行宫，您只要有5级的中心大楼就足够了。在训练好3个拓荒者后，你可以选择地图上一个空白的方块，并点击“建立一座新的村庄”（提示：你必须存有750单位的各种资源），然后您的拓荒者将会离开他们所在的村庄去为您建立新的村庄了。
</p>

<p class="question">如何征服一座村庄？</p>
<p class="answer">
要想征服敌人的村庄，和建立新村庄一样，也必须先要建有1座10级的行宫或皇宫，以及有足够的文明点数。但要注意，敌人的最后一个村庄或者主村是无法征服的。
<br>
<br>
征服敌人的村庄需要领袖（参议员、首领或酋长），他们都需要先在研发所中研发，然后就能在行宫或皇宫中训练出来。需要注意的是，如果已经训练了拓荒者的话，就不能再训练领袖了。领袖跟随自己的军队攻击敌人的村庄若干次，直到敌人村庄的行宫或皇宫被拆掉才能完全征服之。一旦敌村的忠诚度降为0，敌人的村就是你的了。此后你需要重新建一座行宫或皇宫来提升村庄的忠诚度。
</p>
<p class="question">如何获得文明点数？</p>
<p class="answer">
建造或升级建筑都能获得文明点。在行宫或皇宫的讯息中可以看到已获得文明点数，同时还能看到建立新村庄所需要的文明点数。
</p>
<br/>

<table cellspacing="1" cellpadding="2" class="culture_points table_data">
<thead>
    <tr>
        <td colspan="21"><h3>文明点</h3></td>
    </tr>
    <tr>
        <th rowspan="2">建筑</th>
        <th colspan="20">等级</th>
    </tr>
    <tr>
        <th>1</th>
        <th>2</th>
        <th>3</th>
        <th>4</th>
        <th>5</th>
        <th>6</th>
        <th>7</th>
        <th>8</th>
        <th>9</th>
        <th>10</th>
        <th>11</th>
        <th>12</th>
        <th>13</th>
        <th>14</th>
        <th>15</th>
        <th>16</th>
        <th>17</th>
        <th>18</th>
        <th>19</th>
        <th>20</th>
	</tr>
</thead>
<tbody>
	<tr>
		<th class="text">伐木场</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">粘土矿</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">铁矿</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">粮田</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">木材厂</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">砖块厂</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">冶炼厂</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">磨坊</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">面包房</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">仓库</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>18</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>38</td>
	</tr>
	<tr>
		<th class="text">粮仓</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>18</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>38</td>
	</tr>
	<tr>
		<th class="text">铁匠铺</th>
		<td>2</td>
		<td>3</td>
		<td>3</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>10</td>
		<td>12</td>
		<td>15</td>
		<td>18</td>
		<td>21</td>
		<td>26</td>
		<td>31</td>
		<td>37</td>
		<td>44</td>
		<td>53</td>
		<td>64</td>
		<td>77</td>
	</tr>
	<tr>
		<th class="text">防具铺</th>
		<td>2</td>
		<td>3</td>
		<td>3</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>10</td>
		<td>12</td>
		<td>15</td>
		<td>18</td>
		<td>21</td>
		<td>26</td>
		<td>31</td>
		<td>37</td>
		<td>44</td>
		<td>53</td>
		<td>64</td>
		<td>77</td>
	</tr>
	<tr>
		<th class="text">竞技场</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>18</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>38</td>
	</tr>
	<tr>
		<th class="text">中心大楼</th>
		<td>2</td>
		<td>3</td>
		<td>3</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>10</td>
		<td>12</td>
		<td>15</td>
		<td>18</td>
		<td>21</td>
		<td>26</td>
		<td>31</td>
		<td>37</td>
		<td>44</td>
		<td>53</td>
		<td>64</td>
		<td>77</td>
	</tr>
	<tr>
		<th class="text">集结点</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>18</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>38</td>
	</tr>
	<tr>
		<th class="text">市场</th>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>19</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>39</td>
		<td>46</td>
		<td>55</td>
		<td>67</td>
		<td>80</td>
		<td>96</td>
		<td>115</td>
	</tr>
	<tr>
		<th class="text">外交所</th>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>8</td>
		<td>10</td>
		<td>12</td>
		<td>14</td>
		<td>17</td>
		<td>21</td>
		<td>25</td>
		<td>30</td>
		<td>36</td>
		<td>43</td>
		<td>51</td>
		<td>62</td>
		<td>74</td>
		<td>89</td>
		<td>106</td>
		<td>128</td>
		<td>153</td>
	</tr>
	<tr>
		<th class="text">兵营</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>18</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>38</td>
	</tr>
	<tr>
		<th class="text">马厩</th>
		<td>2</td>
		<td>3</td>
		<td>3</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>10</td>
		<td>12</td>
		<td>15</td>
		<td>18</td>
		<td>21</td>
		<td>26</td>
		<td>31</td>
		<td>37</td>
		<td>44</td>
		<td>53</td>
		<td>64</td>
		<td>77</td>
	</tr>
	<tr>
		<th class="text">工场</th>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>19</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>39</td>
		<td>46</td>
		<td>55</td>
		<td>67</td>
		<td>80</td>
		<td>96</td>
		<td>115</td>
	</tr>
	<tr>
		<th class="text">研究院</th>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>8</td>
		<td>10</td>
		<td>12</td>
		<td>14</td>
		<td>17</td>
		<td>21</td>
		<td>25</td>
		<td>30</td>
		<td>36</td>
		<td>43</td>
		<td>51</td>
		<td>62</td>
		<td>74</td>
		<td>89</td>
		<td>106</td>
		<td>128</td>
		<td>153</td>
	</tr>
	<tr>
		<th class="text">地洞</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">市政厅</th>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>10</td>
		<td>12</td>
		<td>15</td>
		<td>18</td>
		<td>21</td>
		<td>26</td>
		<td>31</td>
		<td>37</td>
		<td>45</td>
		<td>53</td>
		<td>64</td>
		<td>77</td>
		<td>92</td>
		<td>111</td>
		<td>133</td>
		<td>160</td>
		<td>192</td>
	</tr>
	<tr>
		<th class="text">行宫</th>
		<td>2</td>
		<td>3</td>
		<td>3</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>10</td>
		<td>12</td>
		<td>15</td>
		<td>18</td>
		<td>21</td>
		<td>26</td>
		<td>31</td>
		<td>37</td>
		<td>44</td>
		<td>53</td>
		<td>64</td>
		<td>77</td>
	</tr>
	<tr>
		<th class="text">皇宫</th>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>10</td>
		<td>12</td>
		<td>15</td>
		<td>18</td>
		<td>21</td>
		<td>26</td>
		<td>31</td>
		<td>37</td>
		<td>45</td>
		<td>53</td>
		<td>64</td>
		<td>77</td>
		<td>92</td>
		<td>111</td>
		<td>133</td>
		<td>160</td>
		<td>192</td>
	</tr>
	<tr>
		<th class="text">藏宝库</th>
		<td>10</td>
		<td>12</td>
		<td>14</td>
		<td>17</td>
		<td>20</td>
		<td>24</td>
		<td>29</td>
		<td>34</td>
		<td>41</td>
		<td>50</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">交易所</th>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>19</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>39</td>
		<td>46</td>
		<td>55</td>
		<td>67</td>
		<td>80</td>
		<td>96</td>
		<td>115</td>
	</tr>
	<tr>
		<th class="text">大兵营</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>18</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>38</td>
	</tr>
	<tr>
		<th class="text">大马厩</th>
		<td>2</td>
		<td>3</td>
		<td>3</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>10</td>
		<td>12</td>
		<td>15</td>
		<td>18</td>
		<td>21</td>
		<td>26</td>
		<td>31</td>
		<td>37</td>
		<td>44</td>
		<td>53</td>
		<td>64</td>
		<td>77</td>
	</tr>
	<tr>
		<th class="text">石匠铺</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>18</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>38</td>
	</tr>
	<tr>
		<th class="text">英雄园</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>18</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>38</td>
	</tr>
</tbody>
</table>

<table cellspacing="1" cellpadding="2" class="table_data" style="table-layout:fixed;">
<thead>
    <tr>
        <td colspan="10"><h3>开拓更多村庄时所需要的文明点数</h3></td>
    </tr>
</thead>
<tbody>
    <tr>
		<th>1</th>
		<th>2</th>
		<th>3</th>
		<th>4</th>
		<th>5</th>
		<th>6</th>
		<th>7</th>
		<th>8</th>
		<th>9</th>
		<th>10</th>
	</tr>
	<tr align="center">
		<td>&nbsp; - &nbsp;</td>
		<td>2000</td>
		<td>8000</td>
		<td>20000</td>
		<td>39000</td>
		<td>65000</td>
		<td>99000</td>
		<td>141000</td>
		<td>191000</td>
		<td>251000</td>
	</tr>
</tbody>
</table>

<p>
当村庄的数量越多时，建立一座新村庄所需要的文明点数也会越多，您不会失去文明点数，然而，您需要更多的文明点数来建立新的村庄。
</p>