<p class="question">How can I found a new village?</p>
<p class="answer">In order to found a new village you need 3 settlers, an empty spot on the map and enough culture points. You do not have to research settlers as you can directly build them with a palace level 10, 15 or 20 or a residence level 10 or 20. To build the palace you need a main building level 5 and an embassy. To build the residence you only need a level 5 main building. After training the 3 settlers you can choose an empty spot on the map and click "Found new village" (Hint: you need 750 units of each resource!) then your settlers will leave their home village and found the new village for you. </p>

<p class="question">How can I conquer a village?</p>
<p class="answer">For this, too, one needs at least a residence/palace level 10 as well as an enemy village one can conquer. Additionally enough culture points are needed - like for founding a new village. One cannot conquer the last of a player's villages and neither their capital.

<br>
<br>

As soon as the steward of a town (senator, chief, chieftain) as been researched in the academy one can train him in the residence/palace like a settler. However, one may not have already trained settlers in order to be able to train a steward. To conquer a village the steward needs to attack the desired village a couple of times after the enemy residence/palace has been demolished. Once the village's loyalty reached zero the village will become one's own. Once this happened one should build a palace or a residence to raise the loyalty again.

<p class="question">How do I get culture points?</p>
<p class="answer">One gets culture points (CPs) by constructing and extending buildings. Already produced culture points can be seen in the residence and palace. Additionally information about the required culture points for additional villages is displayed there.</p>
<br/>

<table cellspacing="1" cellpadding="2" class="culture_points table_data">
<thead>
    <tr>
        <td colspan="21"><h3>文明点</h3></td>
    </tr>
    <tr>
        <th rowspan="2">建筑</th>
        <th colspan="20">等级</th>
    </tr>
    <tr>
        <th>1</th>
        <th>2</th>
        <th>3</th>
        <th>4</th>
        <th>5</th>
        <th>6</th>
        <th>7</th>
        <th>8</th>
        <th>9</th>
        <th>10</th>
        <th>11</th>
        <th>12</th>
        <th>13</th>
        <th>14</th>
        <th>15</th>
        <th>16</th>
        <th>17</th>
        <th>18</th>
        <th>19</th>
        <th>20</th>
	</tr>
</thead>
<tbody>
	<tr>
		<th class="text">伐木场</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">粘土矿</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">铁矿</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">粮田</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">木材厂</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">砖块厂</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">冶炼厂</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">磨坊</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">面包房</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">仓库</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>18</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>38</td>
	</tr>
	<tr>
		<th class="text">粮仓</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>18</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>38</td>
	</tr>
	<tr>
		<th class="text">铁匠铺</th>
		<td>2</td>
		<td>3</td>
		<td>3</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>10</td>
		<td>12</td>
		<td>15</td>
		<td>18</td>
		<td>21</td>
		<td>26</td>
		<td>31</td>
		<td>37</td>
		<td>44</td>
		<td>53</td>
		<td>64</td>
		<td>77</td>
	</tr>
	<tr>
		<th class="text">防具铺</th>
		<td>2</td>
		<td>3</td>
		<td>3</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>10</td>
		<td>12</td>
		<td>15</td>
		<td>18</td>
		<td>21</td>
		<td>26</td>
		<td>31</td>
		<td>37</td>
		<td>44</td>
		<td>53</td>
		<td>64</td>
		<td>77</td>
	</tr>
	<tr>
		<th class="text">竞技场</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>18</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>38</td>
	</tr>
	<tr>
		<th class="text">中心大楼</th>
		<td>2</td>
		<td>3</td>
		<td>3</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>10</td>
		<td>12</td>
		<td>15</td>
		<td>18</td>
		<td>21</td>
		<td>26</td>
		<td>31</td>
		<td>37</td>
		<td>44</td>
		<td>53</td>
		<td>64</td>
		<td>77</td>
	</tr>
	<tr>
		<th class="text">集结点</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>18</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>38</td>
	</tr>
	<tr>
		<th class="text">市场</th>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>19</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>39</td>
		<td>46</td>
		<td>55</td>
		<td>67</td>
		<td>80</td>
		<td>96</td>
		<td>115</td>
	</tr>
	<tr>
		<th class="text">外交所</th>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>8</td>
		<td>10</td>
		<td>12</td>
		<td>14</td>
		<td>17</td>
		<td>21</td>
		<td>25</td>
		<td>30</td>
		<td>36</td>
		<td>43</td>
		<td>51</td>
		<td>62</td>
		<td>74</td>
		<td>89</td>
		<td>106</td>
		<td>128</td>
		<td>153</td>
	</tr>
	<tr>
		<th class="text">兵营</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>18</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>38</td>
	</tr>
	<tr>
		<th class="text">马厩</th>
		<td>2</td>
		<td>3</td>
		<td>3</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>10</td>
		<td>12</td>
		<td>15</td>
		<td>18</td>
		<td>21</td>
		<td>26</td>
		<td>31</td>
		<td>37</td>
		<td>44</td>
		<td>53</td>
		<td>64</td>
		<td>77</td>
	</tr>
	<tr>
		<th class="text">工场</th>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>19</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>39</td>
		<td>46</td>
		<td>55</td>
		<td>67</td>
		<td>80</td>
		<td>96</td>
		<td>115</td>
	</tr>
	<tr>
		<th class="text">研究院</th>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>8</td>
		<td>10</td>
		<td>12</td>
		<td>14</td>
		<td>17</td>
		<td>21</td>
		<td>25</td>
		<td>30</td>
		<td>36</td>
		<td>43</td>
		<td>51</td>
		<td>62</td>
		<td>74</td>
		<td>89</td>
		<td>106</td>
		<td>128</td>
		<td>153</td>
	</tr>
	<tr>
		<th class="text">地洞</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">市政厅</th>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>10</td>
		<td>12</td>
		<td>15</td>
		<td>18</td>
		<td>21</td>
		<td>26</td>
		<td>31</td>
		<td>37</td>
		<td>45</td>
		<td>53</td>
		<td>64</td>
		<td>77</td>
		<td>92</td>
		<td>111</td>
		<td>133</td>
		<td>160</td>
		<td>192</td>
	</tr>
	<tr>
		<th class="text">行宫</th>
		<td>2</td>
		<td>3</td>
		<td>3</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>10</td>
		<td>12</td>
		<td>15</td>
		<td>18</td>
		<td>21</td>
		<td>26</td>
		<td>31</td>
		<td>37</td>
		<td>44</td>
		<td>53</td>
		<td>64</td>
		<td>77</td>
	</tr>
	<tr>
		<th class="text">皇宫</th>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>10</td>
		<td>12</td>
		<td>15</td>
		<td>18</td>
		<td>21</td>
		<td>26</td>
		<td>31</td>
		<td>37</td>
		<td>45</td>
		<td>53</td>
		<td>64</td>
		<td>77</td>
		<td>92</td>
		<td>111</td>
		<td>133</td>
		<td>160</td>
		<td>192</td>
	</tr>
	<tr>
		<th class="text">藏宝库</th>
		<td>10</td>
		<td>12</td>
		<td>14</td>
		<td>17</td>
		<td>20</td>
		<td>24</td>
		<td>29</td>
		<td>34</td>
		<td>41</td>
		<td>50</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<th class="text">交易所</th>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>19</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>39</td>
		<td>46</td>
		<td>55</td>
		<td>67</td>
		<td>80</td>
		<td>96</td>
		<td>115</td>
	</tr>
	<tr>
		<th class="text">大兵营</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>18</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>38</td>
	</tr>
	<tr>
		<th class="text">大马厩</th>
		<td>2</td>
		<td>3</td>
		<td>3</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>10</td>
		<td>12</td>
		<td>15</td>
		<td>18</td>
		<td>21</td>
		<td>26</td>
		<td>31</td>
		<td>37</td>
		<td>44</td>
		<td>53</td>
		<td>64</td>
		<td>77</td>
	</tr>
	<tr>
		<th class="text">石匠铺</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>18</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>38</td>
	</tr>
	<tr>
		<th class="text">英雄园</th>
		<td>1</td>
		<td>1</td>
		<td>2</td>
		<td>2</td>
		<td>2</td>
		<td>3</td>
		<td>4</td>
		<td>4</td>
		<td>5</td>
		<td>6</td>
		<td>7</td>
		<td>9</td>
		<td>11</td>
		<td>13</td>
		<td>15</td>
		<td>18</td>
		<td>22</td>
		<td>27</td>
		<td>32</td>
		<td>38</td>
	</tr>
</tbody>
</table>

<table cellspacing="1" cellpadding="2" class="table_data" style="table-layout:fixed;">
<thead>
    <tr>
        <td colspan="10"><h3>Culture points needed for additional villages</h3></td>
    </tr>
</thead>
<tbody>
    <tr>
		<th>1</th>
		<th>2</th>
		<th>3</th>
		<th>4</th>
		<th>5</th>
		<th>6</th>
		<th>7</th>
		<th>8</th>
		<th>9</th>
		<th>10</th>
	</tr>
	<tr align="center">
		<td>&nbsp; - &nbsp;</td>
		<td>2000</td>
		<td>8000</td>
		<td>20000</td>
		<td>39000</td>
		<td>65000</td>
		<td>99000</td>
		<td>141000</td>
		<td>191000</td>
		<td>251000</td>
	</tr>
</tbody>
</table>

<p>
The more villages one has, the more culture points are necessary to found or conquer additional villages. One cannot lose culture points, however, one needs more for additional villages.
</p>